name: .NET + SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: windows-latest

    steps:
      # 1. Checkout коду
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # або твоя версія

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build project
      - name: Build
        run: dotnet build --no-restore

      # 5. Run tests + generate coverage
      - name: Test with coverage
        run: |
          dotnet test DummyProject.sln `
            /p:CollectCoverage=true `
            /p:CoverletOutputFormat=opencover `
            /p:CoverletOutput=coverage.opencover.xml

      # 6. Begin SonarCloud analysis
      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin `
            /k:"bipolare_reverse-engineering-software" `
            /o:"bipolare" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.cs.opencover.reportsPaths="$(System.DefaultWorkingDirectory)\coverage.opencover.xml"

      # 7. Build again for SonarCloud
      - name: Build for SonarCloud
        run: dotnet build DummyProject.sln

      # 8. End SonarCloud analysis
      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
