name: .NET Build and SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore DummyProject.sln

      - name: Build solution
        run: dotnet build DummyProject.sln --configuration Release

      - name: Begin SonarScanner
        run: |
          dotnet sonarscanner begin /k:"bipolare_reverse-engineering-software" \
                                   /o:"bipolare" \
                                   /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
                                   /d:sonar.cs.opencover.reportsPaths="${{ github.workspace }}\coverage.opencover.xml"
      
      - name: Run tests with coverage
        run: |
          dotnet test DummyProject.sln --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutput="${{ github.workspace }}\coverage.opencover.xml" \
            /p:CoverletOutputFormat=opencover

      - name: End SonarScanner
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
