name: .NET CI with SonarCloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build, Test, Coverage & SonarCloud
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore DummyProject.sln

    - name: Build
      run: dotnet build DummyProject.sln --configuration Release --no-restore

    - name: Run Tests with Coverage
      run: |
        dotnet test DummyProject.sln `
          --configuration Release `
          /p:CollectCoverage=true `
          /p:CoverletOutput="$Env:GITHUB_WORKSPACE\coverage.opencover.xml" `
          /p:CoverletOutputFormat=opencover `
          /p:Exclude="[xunit*]*"
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2.2
      with:
        args: >
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.cs.opencover.reportsPaths="$Env:GITHUB_WORKSPACE\coverage.opencover.xml"
