name: .NET SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_ROOT: C:\Program Files\dotnet
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner tool
        shell: pwsh
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 10.4.1
          $Env:PATH += ";$Env:USERPROFILE\.dotnet\tools"

      - name: Begin SonarCloud analysis
        shell: pwsh
        run: |
          dotnet sonarscanner begin `
            /k:"bipolare_reverse-engineering-software" `
            /o:"bipolare" `
            /d:sonar.login="$Env:SONAR_TOKEN" `
            /d:sonar.cs.opencover.reportsPaths="$Env:GITHUB_WORKSPACE\coverage.opencover.xml"

      - name: Restore dependencies
        run: dotnet restore DummyProject.sln

      - name: Build solution
        run: dotnet build DummyProject.sln --no-restore --configuration Release

      - name: Run tests with coverage
        run: |
          dotnet test DummyProject.sln `
            --no-build `
            --configuration Release `
            /p:CollectCoverage=true `
            /p:CoverletOutput="$Env:GITHUB_WORKSPACE\coverage.opencover.xml" `
            /p:CoverletOutputFormat=opencover

      - name: End SonarCloud analysis
        shell: pwsh
        run: dotnet sonarscanner end /d:sonar.login="$Env:SONAR_TOKEN"
