name: .NET Core + SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    - name: Run tests with coverage
      run: |
        dotnet test DummyProject.sln `
          --configuration Release `
          /p:CollectCoverage=true `
          /p:CoverletOutputFormat=opencover `
          /p:CoverletOutput=$(System.DefaultWorkingDirectory)\coverage.opencover.xml `
          /p:Exclude="[xunit*]*"

    - name: Setup SonarCloud
      uses: SonarSource/sonarcloud-github-action@v2.1.0
      with:
        organization: ${{ secrets.SONAR_ORGANIZATION }}
        token: ${{ secrets.SONAR_TOKEN }}

    - name: Run SonarCloud analysis
      run: |
        dotnet sonarscanner begin /k:"bipolare_reverse-engineering-software" `
          /o:"bipolare" `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.opencover.reportsPaths="$(System.DefaultWorkingDirectory)\coverage.opencover.xml"

        dotnet build DummyProject.sln

        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
